#!/bin/bash
# =============================================================================
# STEP 0: Environment Setup & Software Validation
# AOO GWAS Pipeline
# =============================================================================
# PURPOSE: Create directory structure, validate all required software,
#          and write a config file used by all downstream pipeline steps.
# CHECKPOINT: All tools must pass version checks before proceeding.
# =============================================================================

set -euo pipefail

# ─── USER CONFIG — Edit these paths before running ───────────────────────────
export PHENO_CSV="/path/to/phenotype.csv"
export GENO_PREFIX="/path/to/genotype/all_chr"
export PIPELINE_DIR="/path/to/output/directory"
export THREADS=16        # adjust for your HPC node
export MEMORY=32000      # MB, adjust as needed

# Software paths — update if tools are not in PATH
export PLINK2="plink2"
export REGENIE="regenie"
export RSCRIPT="Rscript"
export PYTHON="python3"
export MAGMA="magma"
# ─────────────────────────────────────────────────────────────────────────────

echo "============================================================"
echo " AOO GWAS PIPELINE — STEP 0: SETUP"
echo "============================================================"

# ─── CREATE DIRECTORY STRUCTURE ──────────────────────────────────────────────
mkdir -p ${PIPELINE_DIR}/{01_phenotype,02_genotype_qc,03_pca,04_gwas/{regenie,cox},\
05_annotation,06_finemapping,07_magma,08_ldsc,09_figures,logs}

echo "[$(date)] Directory structure created."

# ─── CHECKPOINT FUNCTION ─────────────────────────────────────────────────────
checkpoint() {
    local step="$1"
    local condition="$2"
    if eval "$condition"; then
        echo "  ✅ CHECKPOINT PASSED: $step"
    else
        echo "  ❌ CHECKPOINT FAILED: $step"
        echo "     Pipeline halted. Please fix before proceeding."
        exit 1
    fi
}

# ─── SOFTWARE CHECKS ─────────────────────────────────────────────────────────
echo ""
echo "--- Checking required software ---"

PLINK2_VER=$(${PLINK2} --version 2>&1 | head -1 || echo "NOT FOUND")
echo "PLINK2:   $PLINK2_VER"
checkpoint "PLINK2 installed" "echo '$PLINK2_VER' | grep -q 'PLINK'"

REGENIE_VER=$(${REGENIE} --version 2>&1 | head -1 || echo "NOT FOUND")
echo "REGENIE:  $REGENIE_VER"
checkpoint "REGENIE installed" "echo '$REGENIE_VER' | grep -qi 'regenie'"

R_VER=$(${RSCRIPT} --version 2>&1 | head -1 || echo "NOT FOUND")
echo "R:        $R_VER"
checkpoint "R installed" "echo '$R_VER' | grep -q 'R scripting'"

PY_VER=$(${PYTHON} --version 2>&1 || echo "NOT FOUND")
echo "Python:   $PY_VER"
checkpoint "Python installed" "echo '$PY_VER' | grep -q 'Python 3'"

MAGMA_VER=$(${MAGMA} 2>&1 | head -1 || echo "NOT FOUND")
echo "MAGMA:    $MAGMA_VER"

# ─── INPUT FILE CHECKS ───────────────────────────────────────────────────────
echo ""
echo "--- Checking input files ---"

checkpoint "Phenotype CSV exists" "[ -f '${PHENO_CSV}' ]"
echo "  Phenotype file: ${PHENO_CSV}"

for ext in bed bim fam; do
    checkpoint "Genotype .${ext} exists" "[ -f '${GENO_PREFIX}.${ext}' ]"
done
echo "  Genotype prefix: ${GENO_PREFIX}"

# ─── R PACKAGE CHECKS ────────────────────────────────────────────────────────
echo ""
echo "--- Checking R packages ---"

${RSCRIPT} - <<'RCHECK'
required <- c("data.table","ggplot2","ggrepel","dplyr","tidyr",
              "survival","survminer","qqman","CMplot","coloc",
              "susieR","SKAT","RColorBrewer","gridExtra","knitr",
              "tableone","gtsummary","flextable")
missing <- required[!sapply(required, requireNamespace, quietly=TRUE)]
if (length(missing) > 0) {
    cat("  ⚠️  Missing R packages:", paste(missing, collapse=", "), "\n")
    cat("  Install with: install.packages(c('", paste(missing, collapse="','"), "'))\n", sep="")
} else {
    cat("  ✅ All R packages available\n")
}
RCHECK

# ─── PYTHON PACKAGE CHECKS ───────────────────────────────────────────────────
echo ""
echo "--- Checking Python packages ---"

${PYTHON} - <<'PYCHECK'
import importlib, sys
pkgs = ["pandas","numpy","scipy","matplotlib","seaborn","lifelines","statsmodels"]
missing = [p for p in pkgs if importlib.util.find_spec(p) is None]
if missing:
    print(f"  ⚠️  Missing Python packages: {', '.join(missing)}")
    print(f"  Install with: pip install {' '.join(missing)}")
else:
    print("  ✅ All Python packages available")
PYCHECK

# ─── SAVE CONFIG FILE ────────────────────────────────────────────────────────
cat > ${PIPELINE_DIR}/pipeline_config.sh << CONFIG
#!/bin/bash
# Pipeline configuration — auto-generated by step00_setup.sh
export PHENO_CSV="${PHENO_CSV}"
export GENO_PREFIX="${GENO_PREFIX}"
export PIPELINE_DIR="${PIPELINE_DIR}"
export THREADS=${THREADS}
export MEMORY=${MEMORY}
export PLINK2="${PLINK2}"
export REGENIE="${REGENIE}"
export RSCRIPT="${RSCRIPT}"
export PYTHON="${PYTHON}"
CONFIG

echo ""
echo "============================================================"
echo " STEP 0 COMPLETE ✅"
echo " Config saved to: ${PIPELINE_DIR}/pipeline_config.sh"
echo " Next: Run step01_phenotype_prep.py"
echo "============================================================"
